### ISSUE TITLE
LLVM9 for Nougat, will it work ?

### ISSUE THREAD

**Issue by hmtheboy154** [maurossi/llvm#1]
Hi ! I'm trying to build a nougat image which support LLVM9, I used to test your LLVM8 on Nougat and it works great with Mesa 19.2.8. 
I saw that the current Pie LLVM9 branch is using soong build instead of old Android build. So how can I make it work on nougat ? Or I have to wait for another branch for Android build ?

**Comment by maurossi** [comment]
Hi,
As far as I know, nougat-x86 Android.mk is required due to Kati base build system

In order to port Android.mk build rules on top of llvm 9 branch the procedure is the following:

1. git clone llvm-mirror release_90 branch to external/llvm90
2. git cherry-pick all serie of my ( maurossi) commits from my
nougat-x86_llvm80_release_80 , except the 'DO NOT MERGE' one that replaces
(lib)LLVM with (lib)LLVM80
3. port the additional commits happened in pie-x86 llvm90 history, but keep
them in the (lib)LLVM "space"
4. Now port the post "DO NOT MERGE' commits to Android.mk, still keeping
them in the (lib)LLVM "space"
5. Only at the end modify the full script sequence to replace (lib)LLVM
with (lib)LLVM90
6. Modify back mesa main Android.mk to set libLLVM90 and llvm version 9.0
7. Repeat build and modify Android.mk base on errors (cyclically), commit
each fix tracking the solved building error
8. Port back the additional commits to the (lib)LLVM "space"
9. Re-run Step 5

10. Complete the build and push to github as nougat-x86_llvm90_release_90
branch

Il Mer 12 Feb 2020, 10:10 Huy Minh <notifications@github.com> ha scritto:

**Comment by hmtheboy154** [comment]
Thanks for the answer :D. By the way one more question before I close this Issue, when I build Mesa 19.3.2 with LLVM8 on nougat. I got this error : 

> external/mesa/src/amd/llvm/ac_llvm_util.c:53: error: undefined reference to 'LLVMInitializeAMDGPUDisassembler'
external/mesa/src/gallium/auxiliary/gallivm/lp_bld_init.c:143: error: undefined reference to 'LLVMAddCoroEarlyPass'
external/mesa/src/gallium/auxiliary/gallivm/lp_bld_init.c:144: error: undefined reference to 'LLVMAddCoroSplitPass'
external/mesa/src/gallium/auxiliary/gallivm/lp_bld_init.c:145: error: undefined reference to 'LLVMAddCoroElidePass'
external/mesa/src/gallium/auxiliary/gallivm/lp_bld_init.c:175: error: undefined reference to 'LLVMAddCoroCleanupPass'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

I think this problem might somehow related to the new ACO compiler ?

**Comment by maurossi** [comment]
Have you tried with latest nougat-x86_llvm80_release_80 branch?

**Comment by hmtheboy154** [comment]
Yes I am using it right now

**Comment by maurossi** [comment]
Hi, 
Closing because there is no Issue here.

nougat-x86_llvm80_release_80 branch works as expected

You can try with my mesa branch 19.3.3_nougat-x86,
where you will need to modify Android.mk to use libLLVM80 llvm version 8.0 

Mauro
